feat(front): Рефакторин на архитектуру FSD
IASGroup/Parser pull request #36
Opened 2023-10-29 23:24 UTC by ricardaPoz

Фронт был перенесён на архитектуру **[`Feature-Sliced Design`](https://feature-sliced.design/ru/docs)**

2023-10-30 00:27 UTC, transhumanity-adept requested changes

2023-10-30 00:27 UTC, transhumanity-adept commented on frontend/src/pages/card-list/index.ts
> +export default TaskListPage
Не очень понятное название папки card-list, если это главная страница лучше написать home и т.д

2023-10-30 00:27 UTC, transhumanity-adept commented on frontend/src/pages/index.ts
> +import { createRouter, createWebHistory } from "vue-router";
```suggestion
```

2023-10-30 00:27 UTC, transhumanity-adept commented on frontend/src/pages/index.ts
> +  // },
```suggestion
```

2023-10-30 00:27 UTC, transhumanity-adept commented on frontend/src/entities/tasks/ui/card-card-details/index.vue
> +import { Task } from "../../../../shared/api";
```suggestion
import { Task } from "@/shared/api";
```

2023-10-30 00:27 UTC, transhumanity-adept commented on frontend/src/entities/tasks/model/tasks.ts
> +import { ref, reactive } from "vue";
```suggestion
import { ref } from "vue";
```

2023-10-30 12:24 UTC, ricardaPoz commented on frontend/src/shared/api/typicode/models.ts
> +}
Я сам этим вопросом задавался, когда делал по поводу `entities` и хранения там модели.
Но когда читал и смотрел примеры реализаций проектов с данной архитектурой, то модель хранилась в `shared`.
В `entities` создаётся, например store, где реализуются `CRUD` операции над данными.
Ориентировался по вот этой статье [Слои](https://feature-sliced.design/ru/docs/reference/layers).

По поводу согласования модели с беком. Я только попробовал разметить структуру проекта.
Чуть позже распишу сущности. Мб до того момента, пока не сделаю не закрывать PR.

2023-10-30 12:25 UTC, ricardaPoz commented on frontend/src/pages/card-list/index.ts
> +export default TaskListPage
Хорошо. Внесу изменения.

2023-10-30 12:31 UTC, transhumanity-adept commented on frontend/src/shared/api/typicode/models.ts
> +}
![image](https://github.com/IASGroup/Parser/assets/73099365/809ac049-9a57-4faf-ba28-deb956784901)


В Shared не доменные сущности наверное можно хранить,
Задача парсинга точно доменная сущность

2023-11-11 16:58 UTC, transhumanity-adept approved these changes
Ай какой маладец

2023-11-11 16:59 UTC, merged