Collector task3
IASGroup/Parser pull request #69
Opened 2023-11-30 14:36 UTC by JKsevan

Завершена задача парсинга тегов

2023-12-02 12:45 UTC, transhumanity-adept commented
@Barba10s @JKsevan 
Необходимо обновиться до последних изменений релиза, посмотреть на задачу парсинга апи и добавить новые изменения по аналогии:

- Отсылка новых сообщений прогресса в очередь сообщений

2023-12-02 12:50 UTC, transhumanity-adept requested changes

2023-12-08 15:29 UTC, JKsevan commented
Исправили ошибки

2023-12-08 16:19 UTC, transhumanity-adept submitted a review, later dismissed

2023-12-08 16:19 UTC, transhumanity-adept commented on backend/src/Services/Collector/ParserTasks/Handlers/Tags/ParserTaskTagsHandleService.cs
> +				//List<string> innerTextResults = new List<string>();
```suggestion
```

2023-12-08 16:20 UTC, transhumanity-adept approved these changes

2023-12-08 16:20 UTC, merged